# Generated by Django 4.2.1 on 2023-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='edition_placeholder.png', upload_to=''),
        ),
    ]
