# Generated by Django 4.2.1 on 2023-07-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookreview_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='user_id',
            new_name='user',
        ),
    ]
